services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zero_kiss_test
    volumes:
      - postgres_data_test:/var/lib/postgresql/data

  app:
    build: .
    environment:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:postgres@db:5432/zero_kiss_test
    volumes:
      - .:/app:cached
    depends_on:
      - db

volumes:
  postgres_data_test:
    name: zero_kiss_postgres_data_test
