services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    environment:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:postgres@db:5432/zero_kiss_test
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zero_kiss_test
    volumes:
      - zero_kiss_postgres_data_test:/var/lib/postgresql/data

volumes:
  zero_kiss_postgres_data_test:
