services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zero_kiss_development
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:postgres@db:5432/zero_kiss_development
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data_dev:
    name: zero_kiss_postgres_data_dev
