---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/healthz":
    get:
      summary: Health check
      tags:
      - Health
      responses:
        '200':
          description: ok
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
